### ISSUE TITLE
Notes not working on the deta app

### ISSUE THREAD

**Issue by girikgarg8** [notnotrachit/youlearn#1]
The notes feature on the app is not working, it gives an 500 internal error when I try to access the notes page.

**Comment by notnotrachit** [comment]
Thank You for reporting, Will fix it very soon

**Comment by notnotrachit** [comment]
Hello @girikgarg8 , I have fixed this issue, please update our app on deta space and lemme know if you are still facing any issues

**Comment by girikgarg8** [comment]
It's still showing 500 internal server error, see this link: https://ibb.co/72P0S4G

**Comment by notnotrachit** [comment]
Did you update the app?
I will also double check

**Comment by girikgarg8** [comment]
How do you update the app?

**Comment by notnotrachit** [comment]
go to deta.space, click the options menu on youlearn, you will see an option to update app, 
Or you can also visit [https://deta.space/discovery/@dilutewater/learnrack](https://deta.space/discovery/@dilutewater/learnrack), you will see an update option

**Comment by girikgarg8** [comment]
Hello there, the notes feature is working now, but I wanted to ask, you, can we remove duplicate courses from the app? I accidentally added a course twice, and it is showing twice on the dashboard.

**Comment by notnotrachit** [comment]
Currently, there is no delete option on the app, I will implement it very soon.
However, you can still manually delete the course by editing the deta base content. Even tough I won't recommend it.

I will try to implement it very very soon

**Comment by notnotrachit** [comment]
@girikgarg8 I have added the delete course button, update your app again please
